version: '3.7'
services:
    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: spacefill
            POSTGRES_DB: spacefill
            POSTGRES_PASSWORD: password
        ports:
        - "5432:5432"
        volumes:
        - ./volumes/postgres/:/var/lib/postgresql/

    postgraphile:
        image: graphile/postgraphile:v4.6.0
        ports:
          - 5000:5000
        command: --cors --schema public --enhance-graphiql --retry-on-init-fail --watch
        environment:
          DATABASE_URL: postgres://spacefill:password@postgres:5432/spacefill
          DEBUG: postgraphile:graphql,postgraphile:request,postgraphile:postgres*
