-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Contact.Mutation exposing (..)

import Contact.InputObject
import Contact.Interface
import Contact.Object
import Contact.Scalar
import Contact.ScalarCodecs
import Contact.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CreateContactRequiredArguments =
    { input : Contact.InputObject.CreateContactInput }


{-| Creates a single `Contact`.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
createContact :
    CreateContactRequiredArguments
    -> SelectionSet decodesTo Contact.Object.CreateContactPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
createContact requiredArgs____ object____ =
    Object.selectionForCompositeField "createContact" [ Argument.required "input" requiredArgs____.input Contact.InputObject.encodeCreateContactInput ] object____ (identity >> Decode.nullable)


type alias UpdateContactRequiredArguments =
    { input : Contact.InputObject.UpdateContactInput }


{-| Updates a single `Contact` using its globally unique id and a patch.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
updateContact :
    UpdateContactRequiredArguments
    -> SelectionSet decodesTo Contact.Object.UpdateContactPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
updateContact requiredArgs____ object____ =
    Object.selectionForCompositeField "updateContact" [ Argument.required "input" requiredArgs____.input Contact.InputObject.encodeUpdateContactInput ] object____ (identity >> Decode.nullable)


type alias UpdateContactByIdRequiredArguments =
    { input : Contact.InputObject.UpdateContactByIdInput }


{-| Updates a single `Contact` using a unique key and a patch.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
updateContactById :
    UpdateContactByIdRequiredArguments
    -> SelectionSet decodesTo Contact.Object.UpdateContactPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
updateContactById requiredArgs____ object____ =
    Object.selectionForCompositeField "updateContactById" [ Argument.required "input" requiredArgs____.input Contact.InputObject.encodeUpdateContactByIdInput ] object____ (identity >> Decode.nullable)


type alias DeleteContactRequiredArguments =
    { input : Contact.InputObject.DeleteContactInput }


{-| Deletes a single `Contact` using its globally unique id.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
deleteContact :
    DeleteContactRequiredArguments
    -> SelectionSet decodesTo Contact.Object.DeleteContactPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteContact requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteContact" [ Argument.required "input" requiredArgs____.input Contact.InputObject.encodeDeleteContactInput ] object____ (identity >> Decode.nullable)


type alias DeleteContactByIdRequiredArguments =
    { input : Contact.InputObject.DeleteContactByIdInput }


{-| Deletes a single `Contact` using a unique key.

  - input - The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.

-}
deleteContactById :
    DeleteContactByIdRequiredArguments
    -> SelectionSet decodesTo Contact.Object.DeleteContactPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteContactById requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteContactById" [ Argument.required "input" requiredArgs____.input Contact.InputObject.encodeDeleteContactByIdInput ] object____ (identity >> Decode.nullable)
