-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Contact.Object exposing (..)


type Contact
    = Contact


type ContactsConnection
    = ContactsConnection


type ContactsEdge
    = ContactsEdge


type CreateContactPayload
    = CreateContactPayload


type DeleteContactPayload
    = DeleteContactPayload


type PageInfo
    = PageInfo


type UpdateContactPayload
    = UpdateContactPayload
