-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Contact.ScalarCodecs exposing (..)

import Contact.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Cursor =
    Contact.Scalar.Cursor


type alias Datetime =
    Contact.Scalar.Datetime


type alias Id =
    Contact.Scalar.Id


type alias Uuid =
    Contact.Scalar.Uuid


codecs : Contact.Scalar.Codecs Cursor Datetime Id Uuid
codecs =
    Contact.Scalar.defineCodecs
        { codecCursor = defaultCodecs.codecCursor
        , codecDatetime = defaultCodecs.codecDatetime
        , codecId = defaultCodecs.codecId
        , codecUuid = defaultCodecs.codecUuid
        }
