-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Contact.Object.ContactsConnection exposing (..)

import Contact.InputObject
import Contact.Interface
import Contact.Object
import Contact.Scalar
import Contact.ScalarCodecs
import Contact.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A list of `Contact` objects.
-}
nodes :
    SelectionSet decodesTo Contact.Object.Contact
    -> SelectionSet (List (Maybe decodesTo)) Contact.Object.ContactsConnection
nodes object____ =
    Object.selectionForCompositeField "nodes" [] object____ (identity >> Decode.nullable >> Decode.list)


{-| A list of edges which contains the `Contact` and cursor to aid in pagination.
-}
edges :
    SelectionSet decodesTo Contact.Object.ContactsEdge
    -> SelectionSet (List decodesTo) Contact.Object.ContactsConnection
edges object____ =
    Object.selectionForCompositeField "edges" [] object____ (identity >> Decode.list)


{-| Information to aid in pagination.
-}
pageInfo :
    SelectionSet decodesTo Contact.Object.PageInfo
    -> SelectionSet decodesTo Contact.Object.ContactsConnection
pageInfo object____ =
    Object.selectionForCompositeField "pageInfo" [] object____ identity


{-| The count of _all_ `Contact` you could get from the connection.
-}
totalCount : SelectionSet Int Contact.Object.ContactsConnection
totalCount =
    Object.selectionForField "Int" "totalCount" [] Decode.int
