-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Contact.Object.Contact exposing (..)

import Contact.InputObject
import Contact.Interface
import Contact.Object
import Contact.Scalar
import Contact.ScalarCodecs
import Contact.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| A globally unique identifier. Can be used in various places throughout the system to identify this single value.
-}
nodeId : SelectionSet Contact.ScalarCodecs.Id Contact.Object.Contact
nodeId =
    Object.selectionForField "ScalarCodecs.Id" "nodeId" [] (Contact.ScalarCodecs.codecs |> Contact.Scalar.unwrapCodecs |> .codecId |> .decoder)


id : SelectionSet Contact.ScalarCodecs.Uuid Contact.Object.Contact
id =
    Object.selectionForField "ScalarCodecs.Uuid" "id" [] (Contact.ScalarCodecs.codecs |> Contact.Scalar.unwrapCodecs |> .codecUuid |> .decoder)


email : SelectionSet String Contact.Object.Contact
email =
    Object.selectionForField "String" "email" [] Decode.string


firstname : SelectionSet (Maybe String) Contact.Object.Contact
firstname =
    Object.selectionForField "(Maybe String)" "firstname" [] (Decode.string |> Decode.nullable)


lastname : SelectionSet (Maybe String) Contact.Object.Contact
lastname =
    Object.selectionForField "(Maybe String)" "lastname" [] (Decode.string |> Decode.nullable)


createdAt : SelectionSet (Maybe Contact.ScalarCodecs.Datetime) Contact.Object.Contact
createdAt =
    Object.selectionForField "(Maybe ScalarCodecs.Datetime)" "createdAt" [] (Contact.ScalarCodecs.codecs |> Contact.Scalar.unwrapCodecs |> .codecDatetime |> .decoder |> Decode.nullable)
