-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Contact.Object.PageInfo exposing (..)

import Contact.InputObject
import Contact.Interface
import Contact.Object
import Contact.Scalar
import Contact.ScalarCodecs
import Contact.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| When paginating forwards, are there more items?
-}
hasNextPage : SelectionSet Bool Contact.Object.PageInfo
hasNextPage =
    Object.selectionForField "Bool" "hasNextPage" [] Decode.bool


{-| When paginating backwards, are there more items?
-}
hasPreviousPage : SelectionSet Bool Contact.Object.PageInfo
hasPreviousPage =
    Object.selectionForField "Bool" "hasPreviousPage" [] Decode.bool


{-| When paginating backwards, the cursor to continue.
-}
startCursor : SelectionSet (Maybe Contact.ScalarCodecs.Cursor) Contact.Object.PageInfo
startCursor =
    Object.selectionForField "(Maybe ScalarCodecs.Cursor)" "startCursor" [] (Contact.ScalarCodecs.codecs |> Contact.Scalar.unwrapCodecs |> .codecCursor |> .decoder |> Decode.nullable)


{-| When paginating forwards, the cursor to continue.
-}
endCursor : SelectionSet (Maybe Contact.ScalarCodecs.Cursor) Contact.Object.PageInfo
endCursor =
    Object.selectionForField "(Maybe ScalarCodecs.Cursor)" "endCursor" [] (Contact.ScalarCodecs.codecs |> Contact.Scalar.unwrapCodecs |> .codecCursor |> .decoder |> Decode.nullable)
